### ISSUE TITLE
Need help maintaining this repo?

### ISSUE THREAD

**Issue by nodeselector** [alexlafroscia/alfred-switch-audio-source#12]
Looking through open pull requests and issues it seems you're a bit strapped for time at the moment. I'd like to offer helping maintain the project.

**Comment by alexlafroscia** [comment]
Whew, sorry I didn't see this until now!

Honestly, I don't use this Alfred plugin at all and don't code in Python, so I would _love_ the help.

**Comment by alexlafroscia** [comment]
I sent you an invite as a collaborator; feel free to do whatever with this that you want to 👍

**Comment by nodeselector** [comment]
@alexlafroscia could you resend it? The link has expired.  🙇

**Comment by alexlafroscia** [comment]
@nodeselector done!
