### ISSUE TITLE
Setting Environment Variable

### ISSUE THREAD

**Issue by UTH-Tuan** [alexlafroscia/alfred-switch-audio-source#7]
Can you provide some details (screenshots) on how to set the environment variable for less advanced Alfred users?

**Comment by alexlafroscia** [comment]
That's a great idea!

Do you think that a link to the Alfred documentation on workflow variables would be sufficient instead?

https://www.alfredapp.com/help/workflows/advanced/variables/

**Comment by UTH-Tuan** [comment]
Would prefer something straight-forward that wouldn't take more than few minutes to accomplish step 4. Screenshots and text perhaps? Been on step 4 for the last 30 minutes.

**Comment by alexlafroscia** [comment]
Alright, I added some more screenshots to the `README` -- hopefully that makes it easier to set up!
