### ISSUE TITLE
somehow does not work anymore with SwitchAudioSource 1.1.0

### ISSUE THREAD

**Issue by dreimsbach** [alexlafroscia/alfred-switch-audio-source#8]
There was a update to  SwitchAudioSource 1.1.0 yesterday and they changed something in their command line stuff. Your python scripts seems to be broken with that somehow?

Alfred Logging shows this
11:38:13.567] Logging Started...
[11:38:16.845] Switch Audio[Script Filter] Queuing argument '(null)'
[11:38:16.961] Switch Audio[Script Filter] Script with argv '(null)' finished
[11:38:16.963] Switch Audio[Script Filter] {"items": []}

**Comment by maxacarvalho** [comment]
Same here 😢

**Comment by dreimsbach** [comment]
i created a pull request that solved it (for me) 
see pull requests

**Comment by stacksjb** [comment]
Same issue as well.

**Comment by a-marionette** [comment]
Same issue

**Comment by enmanuel-tashi** [comment]
Not working :(

**Comment by nodeselector** [comment]
FYI, fixed by this PR. https://github.com/alexlafroscia/alfred-switch-audio-source/pull/10

**Comment by nodeselector** [comment]
Release that includes @dreimsbach's fix is available: https://github.com/alexlafroscia/alfred-switch-audio-source/releases/tag/v1.3.1
